"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { DownloadCloud, Loader2 } from "lucide-react";

export function ExportCSVButton() {
    const [isExporting, setIsExporting] = useState(false);

    async function handleExport() {
        setIsExporting(true);
        try {
            const response = await fetch("/api/admin/export");
            if (!response.ok) {
                throw new Error("Export failed");
            }

            // Trigger raw browser download
            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.style.display = "none";
            a.href = url;

            // Extract filename from the Content-Disposition header generated by the server
            const contentDisposition = response.headers.get("Content-Disposition");
            let filename = `lms_analytics_export_${new Date().toISOString().split('T')[0]}.csv`;
            if (contentDisposition && contentDisposition.includes("filename=")) {
                const match = contentDisposition.match(/filename="?([^"]+)"?/);
                if (match && match[1]) filename = match[1];
            }

            a.download = filename;
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
            document.body.removeChild(a);
        } catch (error) {
            console.error(error);
            alert("Failed to export analytics data. Please try again.");
        } finally {
            setIsExporting(false);
        }
    }

    return (
        <Button onClick={handleExport} disabled={isExporting} variant="outline" className="border-primary/50 text-primary hover:bg-primary/10 bg-transparent shadow-[0_0_15px_rgba(100,60,255,0.1)]">
            {isExporting ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <DownloadCloud className="w-4 h-4 mr-2" />}
            Export Analytics CSV
        </Button>
    );
}
